apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: logging
spec:
  selector:
    app: tempo
  ports:
    - protocol: TCP
      port: 3200
      targetPort: 3200
      name: tempo
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: zipkin
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo-deployment
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo

    spec:
      containers:
        - name: tempo
          image: grafana/tempo:latest
          args:
            - '--config.file=/etc/tempo/tempo.yml'
          ports:
            - containerPort: 3200
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tempo
              name: tempo-config
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-cm
            defaultMode: 420
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-cm
  namespace: logging
data:
  tempo.yml: |-
    server:
      http_listen_port: 3200
    distributor:
      receivers:
        zipkin:
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/blocks
    metrics_generator:
      registry:
        external_labels:
          source: tempo
      storage:
        path: /tmp/tempo/generator/wal
        remote_write:
          - url: http://prometheus-service.monitoring.svc:9090/api/v1/write
            send_exemplars: true
    overrides:
      metrics_generator_processors: [service-graphs, span-metrics]